[general]
import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
opacity = 0.97
padding = { x = 0, y = 0}
position = { x = 350, y = 80}
dimensions = { columns = 110, lines = 35}

[font]
normal = { family = "monospace", style = "Regular" }
size = 14.0

[env]
TERM = "xterm-256color"
